<a href="https://colab.research.google.com/github/larissafcerqueira/materias_estudos/blob/main/Acessar_sheets_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arquivo utilizado:
https://docs.google.com/spreadsheets/d/16_wtlTJfCq5ByMFddiPY8rLqEDGWGPid2REGK9r3mho/edit?gid=0#gid=0

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQSoxLqGPxo8X9DoW0_EMa1HTCGVROQqhOhLBJQKcoN1tYCNATSRIXRMcfL86nHMn1t7J6Z92xiWQ53/pub?gid=0&single=true&output=csv')
display(df)

,matricula,nome,cidade,estado,pais,idade,departamento,cargo,salario,escolaridade,nota
0,1,Lucas,Atibaia,SP,Brasil,35,Compras,Gerente,"R$ 25.000,00",Superior,8
1,2,Ana,São Paulo,SP,Brasil,29,Vendas,Coordenador,"R$ 12.000,00",Superior,6
2,3,Luiza,Santos,SP,Brasil,38,Finanças,Gerente,"R$ 28.000,00",MBA,9
3,4,Fernando,Atibaia,SP,Brasil,36,Marketing,Diretor,"R$ 40.000,00",Mestrado,7
4,5,Sandra,Atibaia,SP,Brasil,28,Produção,Analista,"R$ 23.000,00",Superior,5
5,6,Douglas,Bragança,SP,Brasil,29,Finanças,Analista,"R$ 11.000,00",Superior,9
6,7,Eduardo,Extrema,MG,Brasil,30,Marketing,Gerente,"R$ 12.000,00",MBA,4
7,8,Ester,Itapeva,MG,Brasil,29,Compras,Analista,"R$ 10.000,00",Superior,2
8,9,Pedro,Extrema,MG,Brasil,30,Marketing,Analista,"R$ 13.000,00",Superior,1
9,10,Maria,Extrema,MG,Brasil,40,Produção,Analista,"R$ 12.000,00",MBA,7

para pegar o link da planilha vá em
'Publicar na web'
selecione a página que quer acessar no df
e após selecione a opção valores separados por virgula
clique em ok
e copie o link para inserir no df

# LER CSV

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/AED - Página1.csv')
print(df)

In [ ]:
display(df)